Repository juliett-golf-hotel/web-app, pull requests merged in 2018-03, with the labels that each got.

#43 Started the styling the weekly and hourly pages
  _config.yml
  _includes/css/main.css
  _layouts/default.html
  fake.html
  hourly.html
  images/cloud-update.svg
  images/cloud.svg
  images/humidity-update.svg
  images/snow-update.svg
  patterns/popup.html
  weekly.html
Labels: content, design, dev, enhancement

#44 Nav
  _includes/css/grids.css
  _includes/css/main.css
  _layouts/default.html
  images/nav-close.svg
  images/nav-menu.svg
  patterns/buttons.css
Labels: content, design, dev

#45 Removed grids.css because there is already a grid.css
  _includes/css/grids.css
  patterns/buttons.css
Labels: bug, dev

#46 Cards
  _includes/css/main.css
  _layouts/default.html
  patterns/buttons.css
  patterns/cards.css
  patterns/cards.html
Labels: content, design, dev

#47 Styled nav to align content neatly
  _includes/css/grid.css
  _includes/css/main.css
  _layouts/default.html
Labels: bug, dev

#48 made footer and added images
  _includes/css/main.css
  _layouts/default.html
  images/large.jpg
  images/medium.jpg
  images/small.jpg
Labels: content, design, dev

#49 made favicon
  _layouts/default.html
  favicon.ico
Labels: content, design

#55 Fixed the icon sizes for the weekly and hourly pages
  hourly.html
  weekly.html
Labels: bug, design, dev

#56 Styled and positioned popup window
  _includes/css/main.css
  _layouts/default.html
  index.html
  patterns/popup.html
Labels: content, design, dev, enhancement

#57 Changed cards a bit and added them to index.html
  index.html
  patterns/cards.css
  patterns/cards.html
Labels: content, design, enhancement

#58 Added banner image and text
  _includes/css/main.css
  _layouts/default.html
  index.html
Labels: content, design, dev

#59 Made button to appear over hero banner
  _includes/css/main.css
  index.html
Labels: bug, content, dev

#65 Changes to work
  index.html
Labels: bug, dev
