Repository juliett-golf-hotel/web-app, pull requests merged in 2018-02, with the labels that each got.

#18 Index startup
  _layouts/default.html
  fake.html
  index.html
Labels: bug, dev

#29 Defined primary and secondary fonts
  common/theme.css
Labels: design, dev

#21 added heading
  fake.html
Labels: bug, dev

#20 Added heading
  fake.html
Labels: bug, dev

#19 Added temporary heading
  fake.html
Labels: bug, dev

#30 added images
  images/cloud.svg
  images/humidity.svg
  images/logo16.svg
  images/logo256.svg
  images/logo32.svg
  images/logo64.svg
  images/snow.svg
  images/sunrise.svg
  images/sunset.svg
  images/wind.svg
Labels: design

#34 Began to create popup window
  _config.yml
  _includes/css/grid.css
  _includes/css/main.css
  _includes/css/modules.css
  _includes/css/type.css
  _layouts/default.html
  css/weather.css
  patterns/popup.css
  patterns/popup.html
Labels: content, dev
